global using System;
global using System.Collections.Generic;
global using System.IO;
global using System.Linq;
global using OpenTK;
global using OpenTK.Windowing.Common;
global using OpenTK.Windowing.Desktop;
global using OpenTK.Mathematics;
global using OpenTK.Graphics.OpenGL;
global using GL = OpenTK.Graphics.OpenGL.GL;
global using SVector2 = System.Numerics.Vector2;
global using SVector3 = System.Numerics.Vector3;
global using SVector4 = System.Numerics.Vector4;
global using MouseButton = OpenTK.Windowing.GraphicsLibraryFramework.MouseButton;
global using Key = OpenTK.Windowing.GraphicsLibraryFramework.Keys;
