name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    env:
      Solution_Name: Graybox.sln
      Project_Path: Graybox.Editor/Graybox.Editor.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Restore dependencies
      run: dotnet restore $env:Project_Path

    - name: Build
      run: dotnet build $env:Project_Path --configuration Release --no-restore

    - name: Publish
      run: dotnet publish $env:Project_Path --configuration Release --no-build --output ./publish

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Graybox.Editor
        path: ./publish